### ISSUE TITLE
missing

### ISSUE THREAD

**Issue by prxpostern** [Dofamin/MTProxy-Docker#7]
where is entrypoint.sh ????

**Comment by Dofamin** [comment]
As described in the [dockerfile](https://github.com/Dofamin/MTProxy-Docker/blob/main/Dockerfile#L7), all files from the folder container-image-root are copied to root folder
but in case you not familiar with ui of github, file is there [entrypoint.sh](https://github.com/Dofamin/MTProxy-Docker/blob/main/container-image-root/entrypoint.sh)
